### ISSUE TITLE
Kodi ebuild

### ISSUE THREAD

**Issue by maggu2810** [MathyV/gentoo-overlay-mathy#1]
Hello,
I found your overlay in the comment on the gentoo bump kodi bug (https://bugs.gentoo.org/show_bug.cgi?id=526992). There is also another kodi-14.0 ebuild in an overlay hosted on github (https://github.com/frace/kodi-overlay/blob/master/media-tv/kodi/kodi-14.0.ebuild). Perhaps you should join your efforts (I am using Kodi now, so I will try to help, too).

**Comment by MathyV** [comment]
Hi there,

That's okay for me, I just created the overlay to be able to use it on my various devices, it's been a long time since I did serious effort on writing quality ebuilds though

Mathy

On January 14, 2015 1:21:17 PM GMT+01:00, Markus Rathgeb notifications@github.com wrote:

> Hello,
> I found your overlay in the comment on the gentoo bump kodi bug
> (https://bugs.gentoo.org/show_bug.cgi?id=526992). There is also another
> kodi-14.0 ebuild in an overlay hosted on github
> (https://github.com/frace/kodi-overlay/blob/master/media-tv/kodi/kodi-14.0.ebuild).
> Should we join our efforts?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MathyV/gentoo-overlays-media/issues/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by frace** [comment]
Hi @MathyV 

@maggu2810 [notified](https://github.com/frace/kodi-overlay/issues/19) me about your overlay and I have to agree that we could merge our efforts. My overlay exists on github since around mid 2013, so there are already contributors sending pull requests since then. So if you don't mind you could contribute to the [kodi-overlay](https://github.com/frace/kodi-overlay) instead to your own.

Cheers
